Homework2
java-park-mail-ru/epochmak-02-2017 pull request #3
Opened 2017-04-03 21:48 UTC by FVarya

2017-04-05 00:24 UTC, d-frolov requested changes
Общее по коду - пробегитесь и посмотрите инспекции и чего они хотят. 
И еще кое где паразитные зависимости в декларации остались

2017-04-05 00:24 UTC, d-frolov commented on src/main/java/techpark/DAO/RequestUsersDAO.java
> + * Created by Варя on 28.03.2017.
Ох, Варя, а зачем вы сделали еще и интефейс к DAO? Ну это же явно лишнее. Тем более, что в AccountService у вас ссылка private final RequestUsersDAOImpl usersDAO;

2017-04-05 00:24 UTC, d-frolov commented on src/main/java/techpark/DAO/RequestUsersDAO.java
> +    String changeUser(@NotNull String oldLogin, @Nullable String login, @Nullable String mail, @Nullable String password);
Если вы начали размечать интерфейс или класс аннотациями @NotNull, то делайте это честно и до конца.
Все параметры должны быть помечены, и все возвращаемые значения.

2017-04-05 00:24 UTC, d-frolov commented on src/main/java/techpark/service/AccountService.java
>  public class AccountService {
Вот выделять интерфейс из AccountСервиса более логично...

2017-04-05 00:24 UTC, d-frolov commented on src/main/java/techpark/service/AccountService.java
> +    private final RequestUsersDAOImpl usersDAO;
Вот это плохая история хранить ссылку на DAO
JdbcTemplate - у вас hread-safe - см его описание в коде:
NOTE: An instance of this class is thread-safe once configured.

А вот ваше ДАО - нет. Храните ссылку на JdbcTemplate и создавайте new DAO на каждый запрос. Это не дорого.

PS. Я тут не прав. В вашем случае все-таки можно хранить DAO, там нет стейта

2017-04-05 00:24 UTC, d-frolov commented on src/main/java/techpark/controller/UserController.java
> +    public ResponseEntity<?> editUser(@RequestBody GetBody body,  HttpSession httpSession) throws NullPointerException {
А почему не так `ResponseEntity<Response>`?

2017-04-05 00:24 UTC, d-frolov commented on src/main/java/techpark/DAO/RequestUsersDAOImpl.java
> +            return (e.getMessage());
Ой...
Как-то странно отдавать пользователю текст библиотечного exception-а

2017-04-05 00:24 UTC, d-frolov commented on src/main/java/techpark/DAO/RequestUsersDAOImpl.java
> +    public int addUser(String mail, String login, String password) {
А что у вас тут за int возвращается? Зачем? Это JDBC-шный код ответа

2017-04-05 00:24 UTC, d-frolov commented on src/main/java/techpark/controller/UserController.java
>          accountService.register(mail, login, passwordEncoder.encode(password));
Смотрите, какая интересная история получается. Сначала вы проверяете базу на наличие там логина, email, а потом делаете вставку. Но между verifyMail и register  кто-то может уже зарегистрироваться. И что тогда вернет register?

Тут надо либо делать все в одной транзакции, либо сначала делать попытку вставки, а если вылетел Duplicate, то сделать дополнительные проверки, что сообщить пользователю, что конкретно дублируется

2017-04-05 00:24 UTC, d-frolov commented on src/main/java/techpark/DAO/RequestUsersDAOImpl.java
> +        final LinkedList<UserToInfo> userList = new LinkedList<>();
Ой, не надо использовать LinkedList, тем более в таком контексте. Используйте ArrayList

Задачка на дом - есть LinkedList и ArrayList, вы в цикле методом add в конец их вставляете миллион значений. Куда быстрее получится и почему?

2017-04-05 00:24 UTC, d-frolov commented on src/main/java/techpark/DAO/RequestUsersDAOImpl.java
> +        } catch (EmptyResultDataAccessException e) {
Ну вы не все исключения таким образом обрабатываете. Хорошо бы на каком-то уровне ловить все исключения от работы с БД (например разрыв соединения) и оборачивать его для пользователя в ErrorResponce.  Иначе у вас просто приложение будет тупо отвалится

2017-04-05 00:24 UTC, d-frolov commented on src/test/java/techpark/service/AccountServiceTest.java
> +        assertNotNull(user);
А user в таком контексте разве может быть null?

2017-04-05 00:24 UTC, d-frolov commented on src/test/java/techpark/service/AccountServiceTest.java
> +        assertEquals(1, row);
Вот мне кажется, что все такие низкоуровневые вещи лучше проверять внутри сервиса, а выше либо возвращать UserData, либо void c Exception если что-то пошло не так. То есть уже когда мы работаем с  AccountService сервисом мы не обязаны знать что-то про БД

2017-04-05 00:24 UTC, d-frolov commented on src/test/java/techpark/service/AccountServiceTest.java
> +@SuppressWarnings("ConstantConditions")
убрать

2017-04-05 00:24 UTC, d-frolov commented on src/test/java/techpark/service/AccountServiceTest.java
> +        System.out.println(user.getScore());
убрать

2017-04-05 18:46 UTC, FVarya commented on src/main/java/techpark/DAO/RequestUsersDAO.java
> + * Created by Варя on 28.03.2017.
интерфейс удалила, добавлять интерфейс accountservice не стала

2017-04-05 18:46 UTC, FVarya commented on src/main/java/techpark/DAO/RequestUsersDAO.java
> +    String changeUser(@NotNull String oldLogin, @Nullable String login, @Nullable String mail, @Nullable String password);
сделала

2017-04-05 18:47 UTC, FVarya commented on src/main/java/techpark/controller/UserController.java
>          accountService.register(mail, login, passwordEncoder.encode(password));
исправила-сначала пытаюсь вставить, потом делаю проверки

2017-04-05 18:48 UTC, FVarya commented on src/main/java/techpark/controller/UserController.java
> +    public ResponseEntity<?> editUser(@RequestBody GetBody body,  HttpSession httpSession) throws NullPointerException {
исправила

2017-04-05 18:53 UTC, FVarya commented on src/main/java/techpark/DAO/RequestUsersDAOImpl.java
> +        } catch (EmptyResultDataAccessException e) {
Добавила данную обработку следующим образом: класс userDAO выбрасывает исключение DataAccessException, исключение пробрасывается через AccountService и обрабатывается уже в классе контроллера. Данный метод мне не очень нравится, но не нашла другого варианта, где исключение можно обработать, и, главное, что вернуть

2017-04-05 18:56 UTC, FVarya commented on src/main/java/techpark/DAO/RequestUsersDAOImpl.java
> +            return (e.getMessage());
убрала проверки на логин и почту в класс контроллера по аналогии с методом регистрации

2017-04-05 19:10 UTC, FVarya commented on src/test/java/techpark/service/AccountServiceTest.java
> +        assertEquals(1, row);
убрала

2017-04-05 19:33 UTC, FVarya commented on src/main/java/techpark/DAO/RequestUsersDAOImpl.java
> +        final LinkedList<UserToInfo> userList = new LinkedList<>();
Из постановки вопроса понятно, что быстрее в ArrayList :D Мне кажется, что это из за того, что список выделяет память под элемент каждый раз, тогда как на массиве выделение происходит не так часто.

2017-04-06 14:14 UTC, d-frolov requested changes

2017-04-06 14:14 UTC, d-frolov commented on src/main/java/techpark/DAO/RequestUsersDAOImpl.java
> +    public ArrayList<UserToInfo> getBestUsers() throws DataAccessException {
`@NotNull`

2017-04-06 14:14 UTC, d-frolov commented on src/main/java/techpark/controller/UserController.java
> +    public ResponseEntity<Response> editUser(@RequestBody GetBody body, HttpSession httpSession) throws NullPointerException {
throws NullPointerException - так не надо делать.  NPE не принято декларировать в методах, а нужно делать проверки на null, так чтоб NPE не вылетало

2017-04-06 14:14 UTC, d-frolov commented on src/main/java/techpark/controller/UserController.java
> +        } catch (DataAccessException e) {
Давайте переделаем архитектуру так, чтоб ничего про работу с БД не вылезало выше AccountService. Исключения в том числе.

2017-04-06 14:14 UTC, d-frolov commented on src/main/java/techpark/DAO/RequestUsersDAOImpl.java
> +        } catch (DuplicateKeyException e) {
Вот что мне не нравится. Вы обрабатывает часть исключений в этом месте - пишете в лог, а часть пробрасываете аж на самый верх, и ничего в лог не пишите. 

По хорошему надо сделать так:
Все исключения ловить на уровне AccountService, по разному обрабатывать, писать в лог, и если очень надо, что наверх пробрасывать уже собcственное исключение AccountServiceException

2017-04-10 21:05 UTC, FVarya commented
Добавила @exceptionhandler для исключения DataAccessException
Проверить работу сервера можно по ссылке: https://gem-td.herokuapp.com/ (но к сожалению он по прежнему не работает в Firefox)
"Голый" сервер: https://gem-td-back.herokuapp.com/

2017-04-11 18:28 UTC, KSolovyev commented
@d-frolov Дима?

2017-04-11 23:14 UTC, d-frolov commented
нормально, спасибо

2017-04-11 23:15 UTC, merged