GameMechanics
java-park-mail-ru/epochmak-02-2017 pull request #4
Opened 2017-04-26 16:02 UTC by FVarya

Игровая механика, но пока без тестов
Папка **pathfinding** взята из интернета и просчитывает путь из лабиринта, путем реализации astar алгоритма

2017-04-26 16:34 UTC, KSolovyev commented
добавьте ссылку на фронт в заголовок пулл реквеста

2017-04-26 20:31 UTC, KSolovyev requested changes

2017-04-26 20:31 UTC, KSolovyev commented on src/main/java/techpark/game/Config.java
> +    public static HashMap<Character, HashMap<String, Double>> TOWERS =
Хочется, чтобы это было через ресурсную систему

2017-04-26 20:31 UTC, KSolovyev commented on src/main/java/techpark/game/base/ServerSnapPart2.java
> +public class ServerSnapPart2 {
![image](https://cloud.githubusercontent.com/assets/4122313/25445782/facd92ca-2ab7-11e7-9f68-969a33647656.png)

2017-04-26 20:31 UTC, KSolovyev commented on src/main/java/techpark/game/internal/ServerSnapshotService.java
> +        if(round == 1) {
почему 1 раунд так отличается?

2017-04-26 20:52 UTC, KSolovyev commented
добавьте ссылку на фронт в заголовок пул-реквеста, пожалуйста

2017-04-26 22:32 UTC, KSolovyev requested changes

2017-04-26 22:32 UTC, KSolovyev commented on src/main/java/techpark/game/GameMechanics.java
> +            searchGame();
давайте вот это тоже через  executor. А то гонки будут

2017-04-26 22:32 UTC, KSolovyev commented on src/main/java/techpark/game/avatar/Square.java
> +    private int absolute(int a) {
Math.abs

2017-04-27 06:35 UTC, FVarya commented
Ссылки на фронт, к сожалению нет совсем :с
Первая часть это расстановка башен, а вторая это уже проход волны мобов.
Сегодня постараюсь написать тесты к рк.
Я пыталась найти реализации конкретных алгоритмов, а именно волнового и astar. По волновому не нашла совсем ничего, по astar было много очень коротких и "только чтобы объяснить принцип" библиотек, так что эта вот единственная толковая, которую нашла.

2017-04-27 08:29 UTC, KSolovyev commented
> Первая часть это расстановка башен, а вторая это уже проход волны мобов.

так давайте их так и назовем. А то непонятно

2017-05-01 20:49 UTC, FVarya commented
Игровые тесты полностью проходят
Только вот на Travis AccountServiceTest перестали проходить, как будто аннотация "@Transactional" игнорируется. При этом все тесты локально на компьютере проходят

2017-05-02 21:23 UTC, KSolovyev commented
как двигается интеграция с фронтом?

2017-05-02 21:25 UTC, KSolovyev commented
как доделаете промежуточные изменения, напишите. Я еще раз посмотрю

2017-05-03 08:00 UTC, FVarya commented
На счет фронтенда - ребята только начали
Промежуточные изменения уже все, переименование папки service в aservice чудесным образом решило мою предыдущую проблему, видимо тесты с аннотацией Transactional должны идти строго последовательно

2017-05-03 14:32 UTC, KSolovyev requested changes

2017-05-03 14:32 UTC, KSolovyev commented on src/main/java/techpark/game/base/ClientSnap.java
> +public class ClientSnap {
У меня тут возник вопрос, а могут два игрока захотеть на одну и ту же клетку поставить башню?

2017-05-03 16:30 UTC, FVarya commented
Захотеть могут 
Но сервер же выстроит их все таки в очередь и кто то из них поставит башню первый, а второй при попытке ткнуть на "невалидную" клетку изменить её уже не сможет. 
Только вот в ответе я никак это  не обозначаю, обоим пользователям возвращается карта с башней, но они не смогут понять кому она пренадлежит. Надо добавить поле, которое будет сообщать о результате  попытки построить башню.

2017-05-03 22:03 UTC, KSolovyev commented
Да, но есть еще один нюанс. После постановки башни одним игроком, другой должен видеть ее не дожидаясь окончания хода. По хорошему он должен видеть курсор, который другой игрок перемещает, но это потребует серьезной переработки движка сервера, поэтому делать  не будем

2017-05-05 16:09 UTC, FVarya commented
Здравствуйте, в дебаг режиме выскакивает следующее исключение(Оно не единственное, но все подобного плана)
![exception](https://cloud.githubusercontent.com/assets/25679933/25753978/4218c0fe-31c6-11e7-9d51-2e66f975c524.jpg)
что может быть причиной?

2017-05-11 10:13 UTC, KSolovyev commented
добавьте ссылку на фронт в заголовке пул-реквеста, пожалуйста

2017-05-12 06:14 UTC, FVarya commented
Она как раз вступила в активную стадию разработки. Как только будут какие-то результаты, добавлю

2017-05-15 14:12 UTC, KSolovyev commented
@FVarya еще нет? 🔥 🔥 🔥  =)

2017-05-15 15:26 UTC, FVarya commented
Уже что то есть
А именно расстановка башен
Волну в консоли можно наблюдать :D 
Добавила ссылку в заголовок

2017-05-18 17:21 UTC, KSolovyev requested changes

2017-05-18 17:21 UTC, KSolovyev commented on pom.xml
> +        <version>1.5.2.RELEASE</version>
1.5.3

2017-05-18 17:21 UTC, KSolovyev commented on src/test/java/techpark/mechanics/GameMechanicsTest.java
> +            e.printStackTrace();
logger

2017-05-18 17:21 UTC, KSolovyev commented on src/test/java/techpark/mechanics/GameMechanicsTest.java
> +            Thread.sleep(700);
зачем это нужно?

2017-05-18 17:21 UTC, KSolovyev commented on src/main/java/techpark/game/GameMechanics.java
> +                e.printStackTrace();
logger

2017-05-19 14:55 UTC, FVarya commented
Если вопрос про Thread.sleep(), то я это делаю для того, чтобы успели пройти внесенные изменения

2017-05-22 11:57 UTC, KSolovyev commented
Так делать не стоит. Лучше тогда при постановке задачи возвращать Future и дожидаться его выполнения

2017-05-22 11:57 UTC, KSolovyev commented
Доделывай и будем мержить

2017-05-22 15:41 UTC, FVarya commented
Я правильно понимаю, что мне нужно изменять функции, чтобы они наследовали интерфейс Future?

2017-05-23 11:06 UTC, KSolovyev commented
Нет, неправильно. Задача, при постановке в ThreadPoolExecutor, возвращает Future. Вот этот future надо взять в тестах и сделать get(). Поток приостановится, пока задача не будет выполнена. Это позволит избавиться от Thread.sleep

2017-05-23 16:02 UTC, FVarya commented
Ура!
Я сделяль :D

2017-05-23 16:31 UTC, KSolovyev requested changes
Еще чуть-чуть

2017-05-23 16:31 UTC, KSolovyev commented on src/main/java/techpark/user/UserProfile.java
> +//    }
убрать закоментированый код

2017-05-24 06:04 UTC, merged